export default [
  { name: '首頁', imgSrc: '', subTitle: '', section: 'section1', svgSrc: '' },
  { name: '一本初心', imgSrc: '', subTitle: '', section: 'section2', svgSrc: '' },
  { name: '二快交通', imgSrc: '', subTitle: '', section: 'section3', svgSrc: '' },
  { name: '三大商圈', imgSrc: '', subTitle: '', section: 'section4', svgSrc: '' },
  { name: '四大團隊', imgSrc: '', subTitle: '', section: 'section5', svgSrc: '' },
  { name: '五大建設', imgSrc: '', subTitle: '', section: 'section6', svgSrc: '' },
  { name: '六項履歷', imgSrc: '', subTitle: '', section: 'section7', svgSrc: '' },
  { name: '七大精品', imgSrc: '', subTitle: '', section: 'section8', svgSrc: '' },
  { name: '八年粉刷', imgSrc: '', subTitle: '', section: 'section9', svgSrc: '' },
  { name: '九大公設', imgSrc: '', subTitle: '', section: 'section10', svgSrc: '' },
  { name: '十年保固', imgSrc: '', subTitle: '', section: 'section11', svgSrc: '' },
  { name: '豐藏完美', imgSrc: '', subTitle: '', section: 'section12', svgSrc: '' },
  { name: '預約賞屋', imgSrc: '', subTitle: '', section: 'contact', svgSrc: '' },
]