export default [
                      
  { name: '首頁', imgSrc: '', subTitle: '', section: 'section1', svgSrc: '', offset: 0 },
  { name: '引言', imgSrc: '', subTitle: '', section: 'section2', svgSrc: '', mobileOffset: 0 },
  { name: '品牌團隊', imgSrc: '', subTitle: '', section: 'section3', svgSrc: '', mobileOffset: 0 },
  { name: '前段地景<br />生活機能', imgSrc: '', subTitle: '', section: 'section4', svgSrc: '', mobileOffset: 0 },
  { name: '學區', imgSrc: '', subTitle: '', section: 'section5', svgSrc: '', 
  mobileOffset: 0 },
  { name: '交通', imgSrc: '', subTitle: '', section: 'section6', svgSrc: '', 
  mobileOffset: 0 },
  { name: '休閒綠地', imgSrc: '', subTitle: '', section: 'section7', svgSrc: '', 
  mobileOffset: 0 },
  { name: '住宅產品', imgSrc: '', subTitle: '', section: 'section8', svgSrc: '', 
  mobileOffset: 0 },
  { name: '團隊實績', imgSrc: '', subTitle: '', section: 'section9', svgSrc: '', 
  mobileOffset: 0 },
  // { name: '', imgSrc: '', subTitle: '', section: 'contact-info', svgSrc: '', mobileOffset: 0, type: 'btn', color: 'orange' },
  // { name: '地圖導航', imgSrc: '', subTitle: '', section: 'google-map', svgSrc: '', mobileOffset: 0, type: 'btn', color: 'blue' },
  // { name: '立即預約', imgSrc: '', subTitle: '', section: 'contact', svgSrc: '', mobileOffset: 0, type: 'btn', color: 'green' },
]
