/* 企業責任 */
export const company = [
  {
    index: 0,
    date: '111/8/27',
    title: '2022公益慈善音樂會',
    subtitle: '',
    desc: '欣聯建設股份有限公司.贊助由社團法人中華兩岸EMBA主辦.「有愛更勇敢」公益慈善音樂會。<br><br>特別邀請蝦米視障人聲樂團、小甜甜音樂藝術製作團隊、黃國倫、楊培安、楊蒨時等歌手與主持人派翠克精彩演出。<br><br>此次活動計畫捐助對象為臺北市四所特殊教育學校、及弱勢視障團體、與偏鄉學生所舉辦的「有愛 更勇敢」公益慈善音樂會，該音樂會是全台唯一對特教學校發起的公益慈善活動。',
    imgs: [
      require('@/projects/shin-lan/shin-lan/csr/3/1.jpg'),
      require('@/projects/shin-lan/shin-lan/csr/3/2.jpg'),
      require('@/projects/shin-lan/shin-lan/csr/3/3.jpg'),
      require('@/projects/shin-lan/shin-lan/csr/3/4.jpg'),
      require('@/projects/shin-lan/shin-lan/csr/3/5.jpg'),
    ],
    slideIndex: 0,
  },
  {
    index: 1,
    date: '111/8/19',
    title: '北投區陽明養護中心',
    subtitle: '欣聯心、傳遞愛、愛心捐贈',
    desc: '欣聯建設機構 林榮三 董事長<br>捐贈 加菜金、奶粉、麥片、電風扇等物資<br>為弱勢團體善盡企業責任。<br><br>#陽明養護中心 原隸屬于台北市啟智協進會，民國六十三年五月在現址正式成立。更名為財團法人台北市私立陽明養護中心。<br><br>本中心為收容智能不足之身心障礙者，在養護期間有系統的訓練，俾能減少其對家庭社會之依賴性，期以增進社會福祉。',
    imgs: [
      require('@/projects/shin-lan/shin-lan/csr/4/1.jpg'),
      require('@/projects/shin-lan/shin-lan/csr/4/2.jpg'),
      require('@/projects/shin-lan/shin-lan/csr/4/3.jpg'),
      require('@/projects/shin-lan/shin-lan/csr/4/4.jpg'),
      require('@/projects/shin-lan/shin-lan/csr/4/5.jpg'),
    ],
    slideIndex: 0,
  },
  {
    index: 2,
    date: '106/9/23',
    title: '陽明教養院',
    subtitle: '陽明教養院敬老關懷演出',
    desc: '於106年9月23日，欣聯建設開發股份有限公司與台科大EMBA SAXOPHONE社團才華，共同聯合向【陽明教養院】長者們做公益性音樂演出及關懷，同時進行院區浴廁、餐廳地板修繕更新，提供院生一個更加舒適的環境。<br><br>障礙，不是生命的全部。生命，還有喜悅和樂符。',
    imgs: [
      require('@/projects/shin-lan/shin-lan/csr/2/img_page2_duty_01.jpg'),
      require('@/projects/shin-lan/shin-lan/csr/2/img_page2_duty_02.jpg'),
      require('@/projects/shin-lan/shin-lan/csr/2/img_page2_duty_03.jpg'),
      require('@/projects/shin-lan/shin-lan/csr/2/img_page2_duty_04.jpg'),
      require('@/projects/shin-lan/shin-lan/csr/2/img_page2_duty_05.jpg'),
    ],
    slideIndex: 0,
  },
  {
    index: 3,
    date: '105/9/3',
    title: '兆如安養中心',
    subtitle: '兆如安養中心敬老關懷演出',
    desc: '由欣聯建設開發股份有限公司，林董事長榮三與曾副總採芳發起，借重莊社長尊輝所帶領的台科大EMBA SAXOPHONE社團才華，於105年9月3日共同聯合向【兆如安養中心】長者們做公益性音樂演出及關懷。<br><br>期許由各自獨立的個體結合成大我的力量回饋社會，並藉由活動異業結盟創造出1+1>2的目標前進。',
    imgs: [
      require('@/projects/shin-lan/shin-lan/csr/1/img_page_duty_01.jpg'),
      require('@/projects/shin-lan/shin-lan/csr/1/img_page_duty_02.jpg'),
      require('@/projects/shin-lan/shin-lan/csr/1/img_page_duty_03.jpg'),
      require('@/projects/shin-lan/shin-lan/csr/1/img_page_duty_04.jpg'),
      require('@/projects/shin-lan/shin-lan/csr/1/img_page_duty_05.jpg'),
      require('@/projects/shin-lan/shin-lan/csr/1/img_page_duty_06.jpg'),
    ],
    slideIndex: 0,
  },

]
